# Data Preparation

## Import Libraries

In [3]:
import numpy as np
import pandas as pd

## Import Data

In [4]:
loan_data_backup = pd.read_csv('loan_data_2007_2014.csv')

C:\Users\marke\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
loan_data = loan_data_backup.copy()

## Explore Data

In [6]:
loan_data

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.00000,36 months,10.65,162.87,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.00000,60 months,15.27,59.83,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.00000,36 months,15.96,84.33,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.00000,36 months,13.49,339.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.00000,60 months,12.69,67.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,1075269,1311441,5000,5000,5000.00000,36 months,7.90,156.46,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,1069639,1304742,7000,7000,7000.00000,60 months,15.96,170.08,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,1072053,1288686,3000,3000,3000.00000,36 months,18.64,109.43,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,1071795,1306957,5600,5600,5600.00000,60 months,21.28,152.39,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,1071570,1306721,5375,5375,5350.00000,60 months,12.69,121.45,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,1070078,1305201,6500,6500,6500.00000,60 months,14.65,153.45,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,1069908,1305008,12000,12000,12000.00000,36 months,12.69,402.54,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,1064687,1298717,9000,9000,9000.00000,36 months,13.49,305.38,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,1069866,1304956,3000,3000,3000.00000,36 months,9.91,96.68,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,1069057,1303503,10000,10000,10000.00000,36 months,10.65,325.74,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,1069759,1304871,1000,1000,1000.00000,36 months,16.29,35.31,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,1065775,1299699,10000,10000,10000.00000,36 months,15.27,347.98,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,1069971,1304884,3600,3600,3600.00000,36 months,6.03,109.57,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,1062474,1294539,6000,6000,6000.00000,36 months,11.71,198.46,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,1069742,1304855,9200,9200,9200.00000,36 months,6.03,280.01,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,1069740,1284848,20250,20250,19142.16108,60 months,15.27,484.63,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21,1039153,1269083,21000,21000,21000.00000,36 months,12.42,701.73,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,1069710,1304821,10000,10000,10000.00000,36 months,11.71,330.76,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,1069700,1304810,10000,10000,10000.00000,36 months,11.71,330.76,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24,1069559,1304634,6000,6000,6000.00000,36 months,11.71,198.46,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,1069697,1273773,15000,15000,15000.00000,36 months,9.91,483.38,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,1069800,1304679,15000,15000,8725.00000,36 months,14.27,514.64,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,1069657,1304764,5000,5000,5000.00000,60 months,16.77,123.65,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,1069799,1304678,4000,4000,4000.00000,36 months,11.71,132.31,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,1047704,1278806,8500,8500,8500.00000,36 months,11.71,281.15,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466255,466255,9776036,11628030,35000,35000,35000.00000,36 months,18.25,1269.73,D,...,NaN,NaN,NaN,NaN,NaN,NaN,153800.0,NaN,NaN,NaN
466256,466256,9835883,9309502,15000,15000,15000.00000,36 months,16.99,534.72,D,...,NaN,NaN,NaN,NaN,NaN,NaN,29300.0,NaN,NaN,NaN
466257,466257,9845880,11697888,12800,12800,12800.00000,36 months,13.53,434.56,B,...,NaN,NaN,NaN,NaN,NaN,NaN,40800.0,NaN,NaN,NaN
466258,466258,9284670,11116818,7000,7000,7000.00000,36 months,9.67,224.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,5000.0,NaN,NaN,NaN
466259,466259,8646060,10418080,18000,18000,17975.00000,36 months,15.61,629.37,C,...,NaN,NaN,NaN,NaN,NaN,NaN,9200.0,NaN,NaN,NaN
466260,466260,9795940,11647977,24000,24000,24000.00000,36 months,21.48,910.13,E,...,NaN,NaN,NaN,NaN,NaN,NaN,33500.0,NaN,NaN,NaN
466261,466261,9824767,11676888,14400,14400,14375.00000,36 months,13.53,488.88,B,...,NaN,NaN,NaN,NaN,NaN,NaN,38100.0,NaN,NaN,NaN
466262,466262,9825193,11677266,14000,14000,14000.00000,36 months,16.24,493.86,C,...,NaN,NaN,NaN,NaN,NaN,NaN,24400.0,NaN,NaN,NaN
466263,466263,9795013,11647121,15250,15250,15250.00000,36 months,17.57,548.05,D,...,NaN,NaN,NaN,NaN,NaN,NaN,40200.0,NaN,NaN,NaN
466264,466264,9765006,11617106,24000,24000,24000.00000,36 months,13.98,820.04,C,...,NaN,NaN,NaN,NaN,NaN,NaN,20400.0,NaN,NaN,NaN
466265,466265,9774870,11626983,32000,32000,31975.00000,36 months,7.90,1001.29,A,...,NaN,NaN,NaN,NaN,NaN,NaN,30800.0,NaN,NaN,NaN
466266,466266,9794642,2217122,12000,12000,12000.00000,36 months,8.90,381.04,A,...,NaN,NaN,NaN,NaN,NaN,NaN,31900.0,NaN,NaN,NaN
466267,466267,9198304,11060277,10000,10000,10000.00000,36 months,12.85,336.22,B,...,NaN,NaN,NaN,NaN,NaN,NaN,25100.0,NaN,NaN,NaN
466268,466268,9646669,11498434,5000,5000,5000.00000,36 months,22.40,191.99,E,...,NaN,NaN,NaN,NaN,NaN,NaN,32700.0,NaN,NaN,NaN
466269,466269,9505043,11337194,13250,13250,13225.00000,60 months,22.90,372.77,E,...,NaN,NaN,NaN,NaN,NaN,NaN,11300.0,NaN,NaN,NaN
466270,466270,9685861,11537845,10000,10000,10000.00000,36 months,7.90,312.91,A,...,NaN,NaN,NaN,NaN,NaN,NaN,32800.0,NaN,NaN,NaN
466271,466271,9656595,11508352,12000,12000,12000.00000,36 months,16.24,423.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,27700.0,NaN,NaN,NaN
466272,466272,9686192,11538048,12000,12000,12000.00000,60 months,21.48,327.89,E,...,NaN,NaN,NaN,NaN,NaN,NaN,26500.0,NaN,NaN,NaN
466273,466273,9199716,11061625,6000,6000,6000.00000,36 months,10.99,196.41,B,...,NaN,NaN,NaN,NaN,NaN,NaN,25400.0,NaN,NaN,NaN
466274,466274,9666300,9890240,10000,10000,10000.00000,36 months,11.99,332.10,B,...,NaN,NaN,NaN,NaN,NaN,NaN,17100.0,NaN,NaN,NaN
466275,466275,9715141,11567259,6000,6000,6000.00000,36 months,15.61,209.79,C,...,NaN,NaN,NaN,NaN,NaN,NaN,10500.0,NaN,NaN,NaN
466276,466276,9695736,11547808,8525,8525,8525.00000,60 months,18.25,217.65,D,...,NaN,NaN,NaN,NaN,NaN,NaN,49800.0,NaN,NaN,NaN
466277,466277,9007579,10799568,18000,18000,17975.00000,36 months,7.90,563.23,A,...,NaN,NaN,NaN,NaN,NaN,NaN,50300.0,NaN,NaN,NaN
466278,466278,9745590,11597671,10000,10000,10000.00000,36 months,18.25,362.78,D,...,NaN,NaN,NaN,NaN,NaN,NaN,11100.0,NaN,NaN,NaN
466279,466279,9745484,11597572,15000,15000,15000.00000,36 months,13.53,509.25,B,...,NaN,NaN,NaN,NaN,NaN,NaN,17600.0,NaN,NaN,NaN
466280,466280,8598660,1440975,18400,18400,18400.00000,60 months,14.47,432.64,C,...,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,466281,9684700,11536848,22000,22000,22000.00000,60 months,19.97,582.50,D,...,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,466282,9584776,11436914,20700,20700,20700.00000,60 months,16.99,514.34,D,...,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,466283,9604874,11457002,2000,2000,2000.00000,36 months,7.90,62.59,A,...,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,466284,9199665,11061576,10000,10000,9975.00000,36 months,19.20,367.58,D,...,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [5]:
pd.options.display.max_columns = None

In [6]:
loan_data

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.00000,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.00,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.70,9.0,f,0.00,0.00,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.0000,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.00000,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.00,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.40,4.0,f,0.00,0.00,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.1100,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.00000,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.50,10.0,f,0.00,0.00,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.0000,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.00000,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.00,37.0,f,0.00,0.00,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.0000,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.00000,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.00,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.90,38.0,f,766.90,766.90,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.0000,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,1075269,1311441,5000,5000,5000.00000,36 months,7.90,156.46,A,A4,Veolia Transportaton,3 years,RENT,36000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,wedding,My wedding loan I promise to pay back,852xx,AZ,11.20,0.0,Nov-04,3.0,NaN,NaN,9.0,0.0,7963,28.30,12.0,f,0.00,0.00,5631.377753,5631.38,5000.00,631.38,0.00,0.00,0.0000,Jan-15,161.03,NaN,Sep-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,1069639,1304742,7000,7000,7000.00000,60 months,15.96,170.08,C,C5,Southern Star Photography,8 years,RENT,47004.00,Not Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/18/11 > I am planning o...,debt_consolidation,Loan,280xx,NC,23.51,0.0,Jul-05,1.0,NaN,NaN,7.0,0.0,17726,85.60,11.0,f,1889.15,1889.15,8136.840000,8136.84,5110.85,3025.99,0.00,0.00,0.0000,Jan-16,170.08,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,1072053,1288686,3000,3000,3000.00000,36 months,18.64,109.43,E,E1,MKC Accounting,9 years,RENT,48000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > Downpayment for...,car,Car Downpayment,900xx,CA,5.35,0.0,Jan-07,2.0,NaN,NaN,4.0,0.0,8221,87.50,4.0,f,0.00,0.00,3938.144334,3938.14,3000.00,938.14,0.00,0.00,0.0000,Jan-15,111.34,NaN,Dec-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,1071795,1306957,5600,5600,5600.00000,60 months,21.28,152.39,F,F2,NaN,4 years,OWN,40000.00,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I own a small h...,small_business,Expand Business & Buy Debt Portfolio,958xx,CA,5.55,0.0,Apr-04,2.0,NaN,NaN,11.0,0.0,5210,32.60,13.0,f,0.00,0.00,646.020000,646.02,162.02,294.94,0.00,189.06,2.0900,Apr-12,152.39,NaN,Aug-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,1071570,1306721,5375,5375,5350.00000,60 months,12.69,121.45,B,B5,Starbucks,< 1 year,RENT,15000.00,Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > I'm trying to b...,other,Building my credit history.,774xx,TX,18.08,0.0,Sep-04,0.0,NaN,NaN,2.0,0.0,9279,36.50,3.0,f,0.00,0.00,1476.190000,1469.34,673.48,533.42,0.00,269.29,2.5200,Nov-12,121.45,NaN,Mar-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,1070078,1305201,6500,6500,6500.00000,60 months,14.65,153.45,C,C3,Southwest Rural metro,5 years,OWN,72000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > I had recived a...,debt_consolidation,High intrest Consolidation,853xx,AZ,16.12,0.0,Jan-98,2.0,NaN,NaN,14.0,0.0,4032,20.60,23.0,f,0.00,0.00,7677.520000,7677.52,6500.00,1177.52,0.00,0.00,0.0000,Jun-13,1655.54,NaN,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,1069908,1305008,12000,12000,12000.00000,36 months,12.69,402.54,B,B5,UCLA,10+ years,OWN,75000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Consolidation,913xx,CA,10.78,0.0,Oct-89,0.0,NaN,NaN,12.0,0.0,23336,67.10,34.0,f,0.00,0.00,13943.080000,13943.08,12000.00,1943.08,0.00,0.00,0.0000,Sep-13,6315.30,NaN,Aug-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,1064687,1298717,9000,9000,9000.00000,36 months,13.49,305.38,C,C1,Va. Dept of Conservation/Recreation,< 1 year,RENT,30000.00,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > Plan to pay off...,debt_consolidation,freedom,245xx,VA,10.08,0.0,Apr-04,1.0,NaN,NaN,4.0,0.0,10452,91.70,9.0,f,0.00,0.00,2270.700000,2270.70,1256.14,570.26,0.00,444.30,4.1600,Jul-12,305.38,NaN,Nov-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,1069866,1304956,3000,3000,3000.00000,36 months,9.91,96.68,B,B1,Target,3 years,RENT,15000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/19/11 > I intend to pay...,credit_card,citicard fund,606xx,IL,12.56,0.0,Jul-03,2.0,NaN,NaN,11.0,0.0,7323,43.10,11.0,f,0.00,0.00,3478.981915,3478.98,3000.00,478.98,0.00,0.00,0.0000,Jan-15,102.43,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,1069057,1303503,10000,10000,10000.00000,36 months,10.65,325.74,B,B2,SFMTA,3 years,RENT,100000.00,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,other,Other Loan,951xx,CA,7.06,0.0,May-91,2.0,NaN,NaN,14.0,0.0,11997,55.50,29.0,f,0.00,0.00,7471.990000,7471.99,5433.47,1393.42,0.00,645.10,6.3145,Oct-13,325.74,NaN,Mar-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,1069759,1304871,1000,1000,1000.00000,36 months,16.29,35.31,D,D1,Internal revenue Service,< 1 year,RENT,28000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation Loan,641xx,MO,20.31,0.0,Sep-07,1.0,NaN,NaN,11.0,0.0,6524,81.50,23.0,f,0.00,0.00,1270.171106,1270.17,1000.00,270.17,0.00,0.00,0.0000,Jan-15,36.32,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,1065775,1299699,10000,10000,10000.00000,36 months,15.27,347.98,C,C4,Chin's Restaurant,4 years,RENT,42000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,Home,921xx,CA,18.60,0.0,Oct-98,2.0,61.0,NaN,14.0,0.0,24043,70.20,28.0,f,0.00,0.00,12519.260450,12519.26,10000.00,2519.26,0.00,0.00,0.0000,Jan-15,370.46,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,1069971,1304884,3600,3600,3600.00000,36 months,6.03,109.57,A,A1,Duracell,10+ years,MORTGAGE,110000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > Payoff other le...,major_purchase,Holiday,067xx,CT,10.52,0.0,Aug-93,0.0,NaN,NaN,20.0,0.0,22836,16.00,42.0,f,0.00,0.00,3785.020000,3785.02,3600.00,185.02,0.00,0.00,0.0000,May-13,583.45,NaN,May-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,1062474,1294539,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,Connection Inspection,1 year,MORTGAGE,84000.00,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > This is a loan ...,medical,Medical,890xx,UT,18.44,2.0,Oct-03,0.0,8.0,NaN,4.0,0.0,0,37.73,14.0,f,0.00,0.00,7164.499852,7164.50,6000.00,1149.50,15.00,0.00,0.0000,Feb-15,16.98,NaN,Jul-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,1069742,1304855,9200,9200,9200.00000,36 months,6.03,280.01,A,A1,Network Interpreting Service,6 years,RENT,77385.19,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,lowerratemeanseasiertogetoutofdebt!,921xx,CA,9.86,0.0,Jan-01,0.0,NaN,NaN,8.0,0.0,7314,23.10,28.0,f,0.00,0.00,9459.960000,9459.96,9200.00,259.96,0.00,0.00,0.0000,Jul-12,8061.10,NaN,Jul-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,1069740,1284848,20250,20250,19142.16108,60 months,15.27,484.63,C,C4,Archdiocese of Galveston Houston,3 years,RENT,43370.00,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,After amassing credit card debt through severa...,debt_consolidation,Freedom From Credit Cards,770xx,TX,26.53,0.0,Nov-97,3.0,NaN,NaN,8.0,0.0,17813,85.60,22.0,f,0.00,0.00,27663.042670,25417.68,20250.00,7413.04,0.00,0.00,0.0000,Aug-15,6024.09,NaN,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21,1039153,1269083,21000,21000,21000.00000,36 months,12.42,701.73,B,B4,Osram Sylvania,10+ years,RENT,105000.00,Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > Decided to clea...,debt_consolidation,Debt Cleanup,335xx,FL,13.22,0.0,Feb-83,0.0,NaN,NaN,7.0,0.0,32135,90.30,38.0,f,0.00,0.00,14025.400000,14025.40,10694.96,3330.44,0.00,0.00,0.0000,Sep-13,701.73,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,1069710,1304821,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,Value Air,10+ years,OWN,50000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/17/11 > Have a stable j...,credit_card,Credit Card Loan,799xx,TX,11.18,0.0,Jul-85,0.0,NaN,NaN,8.0,0.0,10056,82.40,21.0,f,0.00,0.00,11902.561570,11902.56,10000.00,1902.56,0.00,0.00,0.0000,Jan-15,349.21,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,1069700,1304810,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,Wells Fargo Bank,5 years,RENT,50000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation,917xx,CA,16.01,0.0,Apr-03,0.0,NaN,NaN,6.0,0.0,17800,91.80,17.0,f,0.00,0.00,11536.310000,11536.31,10000.00,1536.31,0.00,0.00,0.0000,Oct-13,4942.63,NaN,Mar-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24,1069559,1304634,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,bmg-educational,1 year,RENT,76000.00,Not Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,major_purchase,cash,900xx,CA,2.40,0.0,Jun-01,1.0,NaN,NaN,7.0,0.0,5963,29.70,7.0,f,0.00,0.00,2050.140000,2050.14,1305.58,475.25,0.00,269.31,2.5700,Oct-12,198.46,NaN,Mar-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,1069697,1273773,15000,15000,15000.00000,36 months,9.91,483.38,B,B1,Winfield Pathology Consultants,2 years,MORTGAGE,92000.00,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,No more credit card debt!,605xx,IL,29.44,0.0,Feb-02,0.0,NaN,NaN,8.0,0.0,13707,93.90,31.0,f,0.00,0.00,15823.480000,15823.48,15000.00,823.48,0.00,0.00,0.0000,Sep-12,2447.05,NaN,Sep-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,1069800,1304679,15000,15000,8725.00000,36 months,14.27,514.64,C,C2,nyc transit,9 years,RENT,60000.00,Not Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > looking to cons...,debt_consolidation,consolidation,103xx,NY,15.22,0.0,Oct-03,1.0,NaN,NaN,7.0,0.0,5872,57.60,11.0,f,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,0.00,0.0000,NaN,0.00,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,1069657,1304764,5000,5000,5000.00000,60 months,16.77,123.65,D,D2,Frito Lay,2 years,RENT,50004.00,Not Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > I have a stable...,other,Other,150xx,PA,13.97,3.0,Oct-03,0.0,20.0,NaN,14.0,0.0,4345,59.50,22.0,f,0.00,0.00,1609.120000,1609.12,629.05,719.11,0.00,260.96,2.3000,Dec-12,123.65,NaN,May-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,1069799,1304678,4000,4000,4000.00000,36 months,11.71,132.31,B,B3,Shands Hospital at the University of Fl,10+ years,MORTGAGE,106000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation,326xx,FL,5.63,1.0,Aug-84,0.0,18.0,NaN,12.0,0.0,6110,37.70,44.0,f,0.00,0.00,4484.790000,4484.79,4000.00,484.79,0.00,0.00,0.0000,Apr-13,2638.77,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,1047704,1278806,8500,8500,8500.00000,36 months,11.71,281.15,B,B3,Oakridge homes,< 1 year,RENT,25000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > My loan is for ...,credit_card,Credit card repayment loan,564xx,MN,12.19,0.0,Nov-06,0.0,NaN,NaN,8.0,0.0,6441,59.10,12.0,f,0.00,0.00,10122.208610,10122.21,8500.00,1622.21,0.00,0.00,0.0000,Dec-14,581.59,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466255,466255,9776036,11628030,35000,35000,35000.00000,36 months,18.25,1269.73,D,D3,NaN,9 years,MORTGAGE,284481.00,Source Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,Business Loan,618xx,IL,14.59,0.0,Sep-00,1.0,NaN,NaN,19.0,0.0,119663,65.00,35.0,f,0.00,0.00,43086.889390,43086.89,35000.00,8086.89,0.00,0.00,0.0000,Aug-15,20231.99,NaN,Aug-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,383345.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,153800.0,NaN,NaN,NaN
466256,466256,9835883,9309502,15000,15000,15000.00000,36 months,16.99,534.72,D,D1,NaN,NaN,RENT,50000.00,Source Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/12/13 > bill consolidat...,debt_consolidation,debt consolidation,196xx,PA,24.39,0.0,Apr-01,0.0,NaN,NaN,14.0,0.0,24551,83.80,34.0,f,0.00,0.00,5347.100000,5347.10,3436.71,1910.39,0.00,0.00,0.0000,Nov-14,534.72,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,34157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29300.0,NaN,NaN,NaN
466257,466257,9845880,11697888,12800,12800,12800.00000,36 months,13.53,434.56,B,B5,Chief Information Officer,10+ years,MORTGAGE,113926.00,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,other,Loan 1,351xx,AL,21.55,0.0,Jul-85,0.0,NaN,NaN,12.0,0.0,20804,51.00,37.0,f,0.00,0.00,15178.050000,15178.05,12800.00,2378.05,0.00,0.00,0.0000,Nov-15,6052.29,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,297745.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40800.0,NaN,NaN,NaN
466258,466258,9284670,11116818,7000,7000,7000.00000,36 months,9.67,224.79,B,B1,Welder,10+ years,RENT,100000.00,Source Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,other,Tax Loan,945xx,CA,5.48,0.0,Jun-93,0.0,31.0,NaN,4.0,0.0,2116,42.30,24.0,w,2561.24,2561.24,5394.960000,5394.96,4438.76,956.20,0.00,0.00,0.0000,Jan-16,224.79,Feb-16,Jan-16,0.0,31.0,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,18249.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000.0,NaN,NaN,NaN
466259,466259,8646060,10418080,18000,18000,17975.00000,36 months,15.61,629.37,C,C4,security guard,4 years,RENT,48000.00,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,333xx,FL,31.05,0.0,Apr-85,1.0,24.0,99.0,9.0,1.0,6126,66.60,18.0,f,0.00,0.00,21379.260500,21349.57,18000.00,3379.26,0.00,0.00,0.0000,Jul-15,10680.56,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,32971.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9200.0,NaN,NaN,NaN
466260,466260,9795940,11647977,24000,24000,24000.00000,36 months,21.48,910.13,E,E2,VP of Operations,10+ years,MORTGAGE,210000.00,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Lending Club,463xx,IN,12.98,0.0,Sep-97,3.0,NaN,NaN,23.0,0.0,25713,76.80,39.0,w,9750.13,9750.13,21843.120000,21843.12,14249.87,7593.25,0.00,0.00,0.0000,Jan-16,910.13,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,43547.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33500.0,NaN,NaN,NaN

In [7]:
loan_data.head(4)

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.0,0.0,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
loan_data.tail(4)

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
466281,466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,D5,Chief of Interpretation (Park Ranger),10+ years,MORTGAGE,78000.0,Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,377xx,TN,18.45,0.0,Jun-97,5.0,NaN,116.0,18.0,1.0,18238,46.3,30.0,f,0.00,0.00,4677.920000,4677.92,1837.04,2840.88,0.0,0.0,0.0,Dec-14,17.50,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,221830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,D1,patrol,7 years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/06/13 > I am going to c...,debt_consolidation,Debt consolidation,458xx,OH,25.65,0.0,Dec-01,2.0,65.0,NaN,18.0,0.0,6688,51.1,43.0,f,14428.31,14428.31,12343.980000,12343.98,6271.69,6072.29,0.0,0.0,0.0,Jan-16,514.34,Feb-16,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,73598.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,A4,Server Engineer Lead,3 years,OWN,83000.0,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,913xx,CA,5.39,3.0,Feb-03,1.0,13.0,NaN,21.0,0.0,11404,21.5,27.0,w,0.00,0.00,2126.579838,2126.58,2000.00,126.58,0.0,0.0,0.0,Dec-14,1500.68,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,591610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,D3,NaN,10+ years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > I will like a l...,other,Other,950xx,CA,22.78,1.0,Feb-00,0.0,9.0,NaN,6.0,0.0,11325,70.8,22.0,f,3984.38,3974.41,8821.620000,8799.57,6015.62,2806.00,0.0,0.0,0.0,Jan-16,367.58,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,57477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [9]:
loan_data.columns.values

array(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership',
       'annual_inc', 'verification_status', 'issue_d', 'loan_status',
       'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code',
       'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
       'recoveries', 'collection_recovery_fee', 'last_pymnt_d',
       'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m'],
      dtype=object)

In [10]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 75 columns):
Unnamed: 0                     466285 non-null int64
id                             466285 non-null int64
member_id                      466285 non-null int64
loan_amnt                      466285 non-null int64
funded_amnt                    466285 non-null int64
funded_amnt_inv                466285 non-null float64
term                           466285 non-null object
int_rate                       466285 non-null float64
installment                    466285 non-null float64
grade                          466285 non-null object
sub_grade                      466285 non-null object
emp_title                      438697 non-null object
emp_length                     445277 non-null object
home_ownership                 466285 non-null object
annual_inc                     466281 non-null float64
verification_status            466285 non-null object
issue_d                        466285 non-null object
loan_status                    466285 non-null object
pymnt_plan                     466285 non-null object
url                            466285 non-null object
desc                           125983 non-null object
purpose                        466285 non-null object
title                          466265 non-null object
zip_code                       466285 non-null object
addr_state                     466285 non-null object
dti                            466285 non-null float64
delinq_2yrs                    466256 non-null float64
earliest_cr_line               466256 non-null object
inq_last_6mths                 466256 non-null float64
mths_since_last_delinq         215934 non-null float64
mths_since_last_record         62638 non-null float64
open_acc                       466256 non-null float64
pub_rec                        466256 non-null float64
revol_bal                      466285 non-null int64
revol_util                     465945 non-null float64
total_acc                      466256 non-null float64
initial_list_status            466285 non-null object
out_prncp                      466285 non-null float64
out_prncp_inv                  466285 non-null float64
total_pymnt                    466285 non-null float64
total_pymnt_inv                466285 non-null float64
total_rec_prncp                466285 non-null float64
total_rec_int                  466285 non-null float64
total_rec_late_fee             466285 non-null float64
recoveries                     466285 non-null float64
collection_recovery_fee        466285 non-null float64
last_pymnt_d                   465909 non-null object
last_pymnt_amnt                466285 non-null float64
next_pymnt_d                   239071 non-null object
last_credit_pull_d             466243 non-null object
collections_12_mths_ex_med     466140 non-null float64
mths_since_last_major_derog    98974 non-null float64
policy_code                    466285 non-null int64
application_type               466285 non-null object
annual_inc_joint               0 non-null float64
dti_joint                      0 non-null float64
verification_status_joint      0 non-null float64
acc_now_delinq                 466256 non-null float64
tot_coll_amt                   396009 non-null float64
tot_cur_bal                    396009 non-null float64
open_acc_6m                    0 non-null float64
open_il_6m                     0 non-null float64
open_il_12m                    0 non-null float64
open_il_24m                    0 non-null float64
mths_since_rcnt_il             0 non-null float64
total_bal_il                   0 non-null float64
il_util                        0 non-null float64
open_rv_12m                    0 non-null float64
open_rv_24m                    0 non-null float64
max_bal_bc                     0 non-null float64
all_util                       0 non-null float64
total_rev_hi_lim               396009 non-null float64
inq_fi                         0 non-null float64
total_cu_tl                    0 non-null float64
inq_last_12m                   0 non-null float64
dtypes: float64(46), int64(7), object(22)
memory usage: 266.8+ MB

# General Prepocessing

## Preprocessing few continuous variables 
#### Making sure that our continuous variables are numeric. Data type "object" is text strings that needs to be converted to integers(float64). str.replace will allow to get rid off the text. Then, we will use pandas.to_numeric() to change data type from str to float.

In [11]:
loan_data['emp_length'].unique()

array(['10+ years', '< 1 year', '1 year', '3 years', '8 years', '9 years',
       '4 years', '5 years', '6 years', '2 years', '7 years', nan],
      dtype=object)

In [21]:
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('/+ years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('nan', str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('+', '')
loan_data['emp_length_int'].fillna()

In [22]:
loan_data['emp_length_int'].unique()

array([10.,  0.,  1.,  3.,  8.,  9.,  4.,  5.,  6.,  2.,  7., nan])

In [23]:
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'])

In [24]:
type(loan_data['emp_length_int'][0])

numpy.float64

In [25]:
loan_data['emp_length_int'].isnull().sum()

21008

In [17]:
loan_data['emp_length_int'].unique()

array([10.,  0.,  1.,  3.,  8.,  9.,  4.,  5.,  6.,  2.,  7., nan])

In [18]:
loan_data['emp_length_int'].isnull().sum()

21008

In [30]:
loan_data['emp_length_int'].fillna(value=0, inplace=True)
loan_data['emp_length_int'].isnull().sum()
loan_data['emp_length_int'].unique()

array([10.,  0.,  1.,  3.,  8.,  9.,  4.,  5.,  6.,  2.,  7.])

In [31]:
loan_data['term'].unique()

array([' 36 months', ' 60 months'], dtype=object)

In [32]:
loan_data['term_int'] = loan_data['term'].str.replace(' months', '')
loan_data['term_int'] = pd.to_numeric(loan_data['term_int'])
type(loan_data['term_int'][0])

numpy.int64

In [33]:
loan_data['term_int'].unique()

array([36, 60], dtype=int64)

In [34]:
loan_data

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,emp_length_int,emp_length-int,term_int
0,0,1077501,1296599,5000,5000,4975.00000,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.00,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.70,9.0,f,0.00,0.00,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.0000,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,36
1,1,1077430,1314167,2500,2500,2500.00000,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.00,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.40,4.0,f,0.00,0.00,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.1100,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,60
2,2,1077175,1313524,2400,2400,2400.00000,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.50,10.0,f,0.00,0.00,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.0000,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,36
3,3,1076863,1277178,10000,10000,10000.00000,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.00,37.0,f,0.00,0.00,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.0000,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,36
4,4,1075358,1311748,3000,3000,3000.00000,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.00,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.90,38.0,f,766.90,766.90,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.0000,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,60
5,5,1075269,1311441,5000,5000,5000.00000,36 months,7.90,156.46,A,A4,Veolia Transportaton,3 years,RENT,36000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,wedding,My wedding loan I promise to pay back,852xx,AZ,11.20,0.0,Nov-04,3.0,NaN,NaN,9.0,0.0,7963,28.30,12.0,f,0.00,0.00,5631.377753,5631.38,5000.00,631.38,0.00,0.00,0.0000,Jan-15,161.03,NaN,Sep-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,36
6,6,1069639,1304742,7000,7000,7000.00000,60 months,15.96,170.08,C,C5,Southern Star Photography,8 years,RENT,47004.00,Not Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/18/11 > I am planning o...,debt_consolidation,Loan,280xx,NC,23.51,0.0,Jul-05,1.0,NaN,NaN,7.0,0.0,17726,85.60,11.0,f,1889.15,1889.15,8136.840000,8136.84,5110.85,3025.99,0.00,0.00,0.0000,Jan-16,170.08,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,8.0,60
7,7,1072053,1288686,3000,3000,3000.00000,36 months,18.64,109.43,E,E1,MKC Accounting,9 years,RENT,48000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > Downpayment for...,car,Car Downpayment,900xx,CA,5.35,0.0,Jan-07,2.0,NaN,NaN,4.0,0.0,8221,87.50,4.0,f,0.00,0.00,3938.144334,3938.14,3000.00,938.14,0.00,0.00,0.0000,Jan-15,111.34,NaN,Dec-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,36
8,8,1071795,1306957,5600,5600,5600.00000,60 months,21.28,152.39,F,F2,NaN,4 years,OWN,40000.00,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I own a small h...,small_business,Expand Business & Buy Debt Portfolio,958xx,CA,5.55,0.0,Apr-04,2.0,NaN,NaN,11.0,0.0,5210,32.60,13.0,f,0.00,0.00,646.020000,646.02,162.02,294.94,0.00,189.06,2.0900,Apr-12,152.39,NaN,Aug-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,60
9,9,1071570,1306721,5375,5375,5350.00000,60 months,12.69,121.45,B,B5,Starbucks,< 1 year,RENT,15000.00,Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > I'm trying to b...,other,Building my credit history.,774xx,TX,18.08,0.0,Sep-04,0.0,NaN,NaN,2.0,0.0,9279,36.50,3.0,f,0.00,0.00,1476.190000,1469.34,673.48,533.42,0.00,269.29,2.5200,Nov-12,121.45,NaN,Mar-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,60
10,10,1070078,1305201,6500,6500,6500.00000,60 months,14.65,153.45,C,C3,Southwest Rural metro,5 years,OWN,72000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > I had recived a...,debt_consolidation,High intrest Consolidation,853xx,AZ,16.12,0.0,Jan-98,2.0,NaN,NaN,14.0,0.0,4032,20.60,23.0,f,0.00,0.00,7677.520000,7677.52,6500.00,1177.52,0.00,0.00,0.0000,Jun-13,1655.54,NaN,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,60
11,11,1069908,1305008,12000,12000,12000.00000,36 months,12.69,402.54,B,B5,UCLA,10+ years,OWN,75000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Consolidation,913xx,CA,10.78,0.0,Oct-89,0.0,NaN,NaN,12.0,0.0,23336,67.10,34.0,f,0.00,0.00,13943.080000,13943.08,12000.00,1943.08,0.00,0.00,0.0000,Sep-13,6315.30,NaN,Aug-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,36
12,12,1064687,1298717,9000,9000,9000.00000,36 months,13.49,305.38,C,C1,Va. Dept of Conservation/Recreation,< 1 year,RENT,30000.00,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > Plan to pay off...,debt_consolidation,freedom,245xx,VA,10.08,0.0,Apr-04,1.0,NaN,NaN,4.0,0.0,10452,91.70,9.0,f,0.00,0.00,2270.700000,2270.70,1256.14,570.26,0.00,444.30,4.1600,Jul-12,305.38,NaN,Nov-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,36
13,13,1069866,1304956,3000,3000,3000.00000,36 months,9.91,96.68,B,B1,Target,3 years,RENT,15000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/19/11 > I intend to pay...,credit_card,citicard fund,606xx,IL,12.56,0.0,Jul-03,2.0,NaN,NaN,11.0,0.0,7323,43.10,11.0,f,0.00,0.00,3478.981915,3478.98,3000.00,478.98,0.00,0.00,0.0000,Jan-15,102.43,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,36
14,14,1069057,1303503,10000,10000,10000.00000,36 months,10.65,325.74,B,B2,SFMTA,3 years,RENT,100000.00,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,other,Other Loan,951xx,CA,7.06,0.0,May-91,2.0,NaN,NaN,14.0,0.0,11997,55.50,29.0,f,0.00,0.00,7471.990000,7471.99,5433.47,1393.42,0.00,645.10,6.3145,Oct-13,325.74,NaN,Mar-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,36
15,15,1069759,1304871,1000,1000,1000.00000,36 months,16.29,35.31,D,D1,Internal revenue Service,< 1 year,RENT,28000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation Loan,641xx,MO,20.31,0.0,Sep-07,1.0,NaN,NaN,11.0,0.0,6524,81.50,23.0,f,0.00,0.00,1270.171106,1270.17,1000.00,270.17,0.00,0.00,0.0000,Jan-15,36.32,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,36
16,16,1065775,1299699,10000,10000,10000.00000,36 months,15.27,347.98,C,C4,Chin's Restaurant,4 years,RENT,42000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,Home,921xx,CA,18.60,0.0,Oct-98,2.0,61.0,NaN,14.0,0.0,24043,70.20,28.0,f,0.00,0.00,12519.260450,12519.26,10000.00,2519.26,0.00,0.00,0.0000,Jan-15,370.46,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,36
17,17,1069971,1304884,3600,3600,3600.00000,36 months,6.03,109.57,A,A1,Duracell,10+ years,MORTGAGE,110000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > Payoff other le...,major_purchase,Holiday,067xx,CT,10.52,0.0,Aug-93,0.0,NaN,NaN,20.0,0.0,22836,16.00,42.0,f,0.00,0.00,3785.020000,3785.02,3600.00,185.02,0.00,0.00,0.0000,May-13,583.45,NaN,May-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,36
18,18,1062474,1294539,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,Connection Inspection,1 year,MORTGAGE,84000.00,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > This is a loan ...,medical,Medical,890xx,UT,18.44,2.0,Oct-03,0.0,8.0,NaN,4.0,0.0,0,37.73,14.0,f,0.00,0.00,7164.499852,7164.50,6000.00,1149.50,15.00,0.00,0.0000,Feb-15,16.98,NaN,Jul-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,36
19,19,1069742,1304855,9200,9200,9200.00000,36 months,6.03,280.01,A,A1,Network Interpreting Service,6 years,RENT,77385.19,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,lowerratemeanseasiertogetoutofdebt!,921xx,CA,9.86,0.0,Jan-01,0.0,NaN,NaN,8.0,0.0,7314,23.10,28.0,f,0.00,0.00,9459.960000,9459.96,9200.00,259.96,0.00,0.00,0.0000,Jul-12,8061.10,NaN,Jul-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,36
20,20,1069740,1284848,20250,20250,19142.16108,60 months,15.27,484.63,C,C4,Archdiocese of Galveston Houston,3 years,RENT,43370.00,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,After amassing credit card debt through severa...,debt_consolidation,Freedom From Credit Cards,770xx,TX,26.53,0.0,Nov-97,3.0,NaN,NaN,8.0,0.0,17813,85.60,22.0,f,0.00,0.00,27663.042670,25417.68,20250.00,7413.04,0.00,0.00,0.0000,Aug-15,6024.09,NaN,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,60
21,21,1039153,1269083,21000,21000,21000.00000,36 months,12.42,701.73,B,B4,Osram Sylvania,10+ years,RENT,105000.00,Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > Decided to clea...,debt_consolidation,Debt Cleanup,335xx,FL,13.22,0.0,Feb-83,0.0,NaN,NaN,7.0,0.0,32135,90.30,38.0,f,0.00,0.00,14025.400000,14025.40,10694.96,3330.44,0.00,0.00,0.0000,Sep-13,701.73,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,36
22,22,1069710,1304821,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,Value Air,10+ years,OWN,50000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/17/11 > Have a stable j...,credit_card,Credit Card Loan,799xx,TX,11.18,0.0,Jul-85,0.0,NaN,NaN,8.0,0.0,10056,82.40,21.0,f,0.00,0.00,11902.561570,11902.56,10000.00,1902.56,0.00,0.00,0.0000,Jan-15,349.21,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,36
23,23,1069700,1304810,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,Wells Fargo Bank,5 years,RENT,50000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation,917xx,CA,16.01,0.0,Apr-03,0.0,NaN,NaN,6.0,0.0,17800,91.80,17.0,f,0.00,0.00,11536.310000,11536.31,10000.00,1536.31,0.00,0.00,0.0000,Oct-13,4942.63,NaN,Mar-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,36
24,24,1069559,1304634,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,bmg-educational,1 year,RENT,76000.00,Not Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,major_purchase,cash,900xx,CA,2.40,0.0,Jun-01,1.0,NaN,NaN,7.0,0.0,5963,29.70,7.0,f,0.00,0.00,2050.140000,2050.14,1305.58,475.25,0.00,269.31,2.5700,Oct-12,198.46,NaN,Mar-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,36
25,25,1069697,1273773,15000,15000,15000.00000,36 months,9.91,483.38,B,B1,Winfield Pathology Consultants,2 years,MORTGAGE,92000.00,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,No more credit card debt!,605xx,IL,29.44,0.0,Feb-02,0.0,NaN,NaN,8.0,0.0,13707,93.90,31.0,f,0.00,0.00,15823.480000,15823.48,15000.00,823.48,0.00,0.00,0.0000,Sep-12,2447.05,NaN,Sep-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,36
26,26,1069800,1304679,15000,15000,8725.00000,36 months,14.27,514.64,C,C2,nyc transit,9 years,RENT,60000.00,Not Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > looking to cons...,debt_consolidation,consolidation,103xx,NY,15.22,0.0,Oct-03,1.0,NaN,NaN,7.0,0.0,5872,57.60,11.0,f,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,0.00,0.0000,NaN,0.00,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,36
27,27,1069657,1304764,5000,5000,5000.00000,60 months,16.77,123.65,D,D2,Frito Lay,2 years,RENT,50004.00,Not Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > I have a stable...,other,Other,150xx,PA,13.97,3.0,Oct-03,0.0,20.0,NaN,14.0,0.0,4345,59.50,22.0,f,0.00,0.00,1609.120000,1609.12,629.05,719.11,0.00,260.96,2.3000,Dec-12,123.65,NaN,May-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,60
28,28,1069799,1304678,4000,4000,4000.00000,36 months,11.71,132.31,B,B3,Shands Hospital at the University of Fl,10+ years,MORTGAGE,106000.00,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation,326xx,FL,5.63,1.0,Aug-84,0.0,18.0,NaN,12.0,0.0,6110,37.70,44.0,f,0.00,0.00,4484.790000,4484.79,4000.00,484.79,0.00,0.00,0.0000,Apr-13,2638.77,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,36
29,29,1047704,1278806,8500,8500,8500.00000,36 months,11.71,281.15,B,B3,Oakridge homes,< 1 year,RENT,25000.00,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/15/11 > My loan is for ...,credit_card,Credit card repayment loan,564xx,MN,12.19,0.0,Nov-06,0.0,NaN,NaN,8.0,0.0,6441,59.10,12.0,f,0.00,0.00,10122.208610,10122.21,8500.00,1622.21,0.00,0.00,0.0000,Dec-14,581.59,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466255,466255,9776036,11628030,35000,35000,35000.00000,36 months,18.25,1269.73,D,D3,NaN,9 years,MORTGAGE,284481.00,Source Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,Business Loan,618xx,IL,14.59,0.0,Sep-00,1.0,NaN,NaN,19.0,0.0,119663,65.00,35.0,f,0.00,0.00,43086.889390,43086.89,35000.00,8086.89,0.00,0.00,0.0000,Aug-15,20231.99,NaN,Aug-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,383345.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,153800.0,NaN,NaN,NaN,9.0,9.0,36
466256,466256,9835883,9309502,15000,15000,15000.00000,36 months,16.99,534.72,D,D1,NaN,NaN,RENT,50000.00,Source Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/12/13 > bill consolidat...,debt_consolidation,debt consolidation,196xx,PA,24.39,0.0,Apr-01,0.0,NaN,NaN,14.0,0.0,24551,83.80,34.0,f,0.00,0.00,5347.100000,5347.10,3436.71,1910.39,0.00,0.00,0.0000,Nov-14,534.72,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,34157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29300.0,NaN,NaN,NaN,0.0,0.0,36
466257,466257,9845880,11697888,12800,12800,12800.00000,36 months,13.53,434.56,B,B5,Chief Information Officer,10+ years,MORTGAGE,113926.00,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,other,Loan 1,351xx,AL,21.55,0.0,Jul-85,0.0,NaN,NaN,12.0,0.0,20804,51.00,37.0,f,0.00,0.00,15178.050000,15178.05,12800.00,2378.05,0.00,0.00,0.0000,Nov-15,6052.29,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,297745.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40800.0,NaN,NaN,NaN,10.0,10.0,36
466258,466258,9284670,11116818,7000,7000,7000.00000,36 months,9.67,224.79,B,B1,Welder,10+ years,RENT,100000.00,Source Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,other,Tax Loan,945xx,CA,5.48,0.0,Jun-93,0.0,31.0,NaN,4.0,0.0,2116,42.30,24.0,w,2561.24,2561.24,5394.960000,5394.96,4438.76,956.20,0.00,0.00,0.0000,Jan-16,224.79,Feb-16,Jan-16,0.0,31.0,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,18249.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000.0,NaN,NaN,NaN,10.0,10.0,36
466259,466259,8646060,10418080,18000,18000,17975.00000,36 months,15.61,629.37,C,C4,security guard,4 years,RENT,48000.00,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,333xx,FL,31.05,0.0,Apr-85,1.0,24.0,99.0,9.0,1.0,6126,66.60,18.0,f,0.00,0.00,21379.260500,21349.57,18000.00,3379.26,0.00,0.00,0.0000,Jul-15,10680.56,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,32971.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9200.0,NaN,NaN,NaN,4.0,4.0,36

In [35]:
loan_data['earliest_cr_line']

0         Jan-85
1         Apr-99
2         Nov-01
3         Feb-96
4         Jan-96
5         Nov-04
6         Jul-05
7         Jan-07
8         Apr-04
9         Sep-04
10        Jan-98
11        Oct-89
12        Apr-04
13        Jul-03
14        May-91
15        Sep-07
16        Oct-98
17        Aug-93
18        Oct-03
19        Jan-01
20        Nov-97
21        Feb-83
22        Jul-85
23        Apr-03
24        Jun-01
25        Feb-02
26        Oct-03
27        Oct-03
28        Aug-84
29        Nov-06
           ...
466255    Sep-00
466256    Apr-01
466257    Jul-85
466258    Jun-93
466259    Apr-85
466260    Sep-97
466261    Aug-97
466262    Feb-93
466263    Jul-98
466264    Aug-03
466265    Jul-93
466266    Mar-94
466267    Oct-02
466268    Dec-01
466269    Apr-00
466270    Oct-86
466271    Dec-93
466272    Jun-01
466273    May-90
466274    Aug-83
466275    Nov-93
466276    Nov-94
466277    Jul-98
466278    Jun-02
466279    Aug-99
466280    Apr-03
466281    Jun-97
466282    Dec-01
466283    Feb-03
466284    Feb-00
Name: earliest_cr_line, Length: 466285, dtype: object

In [36]:
loan_data['earliest_cr_line_date'] = pd.to_datetime(loan_data['earliest_cr_line'], format = '%b-%y')

In [37]:
type(loan_data['earliest_cr_line_date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [38]:
pd.to_datetime('2017-12-01') - loan_data['earliest_cr_line_date']

0        12022 days
1         6819 days
2         5874 days
3         7974 days
4         8005 days
5         4778 days
6         4536 days
7         3987 days
8         4992 days
9         4839 days
10        7274 days
11       10288 days
12        4992 days
13        5267 days
14        9711 days
15        3744 days
16        7001 days
17        8888 days
18        5175 days
19        6178 days
20        7335 days
21       12722 days
22       11841 days
23        5358 days
24        6027 days
25        5782 days
26        5175 days
27        5175 days
28       12175 days
29        4048 days
            ...
466255    6300 days
466256    6088 days
466257   11841 days
466258    8949 days
466259   11932 days
466260    7396 days
466261    7427 days
466262    9069 days
466263    7093 days
466264    5236 days
466265    8919 days
466266    8676 days
466267    5540 days
466268    5844 days
466269    6453 days
466270   11384 days
466271    8766 days
466272    6027 days
466273   10076 days
466274   12541 days
466275    8796 days
466276    8431 days
466277    7093 days
466278    5662 days
466279    6697 days
466280    5358 days
466281    7488 days
466282    5844 days
466283    5417 days
466284    6513 days
Name: earliest_cr_line_date, Length: 466285, dtype: timedelta64[ns]

In [39]:
loan_data['mths_since_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - loan_data['earliest_cr_line_date']) / np.timedelta64(1,'M')))

In [40]:
loan_data['mths_since_earliest_cr_line'].describe()

count    466256.000000
mean        239.482430
std          93.974829
min        -612.000000
25%         183.000000
50%         225.000000
75%         285.000000
max         587.000000
Name: mths_since_earliest_cr_line, dtype: float64

In [41]:
type(loan_data['mths_since_earliest_cr_line'][0])

numpy.float64

In [42]:
loan_data.loc[: , ['earliest_cr_line', 'earliest_cr_line_date' , 'mths_since_earliest_cr_line']][loan_data['mths_since_earliest_cr_line'] < 0]

       earliest_cr_line earliest_cr_line_date  mths_since_earliest_cr_line
1580             Sep-62            2062-09-01                       -537.0
1770             Sep-68            2068-09-01                       -609.0
2799             Sep-64            2064-09-01                       -561.0
3282             Sep-67            2067-09-01                       -597.0
3359             Feb-65            2065-02-01                       -566.0
3413             Jun-67            2067-06-01                       -594.0
3607             Aug-67            2067-08-01                       -596.0
3989             Dec-63            2063-12-01                       -552.0
4440             Sep-68            2068-09-01                       -609.0
4449             Sep-68            2068-09-01                       -609.0
4492             Mar-63            2063-03-01                       -543.0
5109             Aug-68            2068-08-01                       -608.0
5417             Nov-65            2065-11-01                       -575.0
5692             May-65            2065-05-01                       -569.0
6137             Oct-54            2054-10-01                       -442.0
6435             Jun-68            2068-06-01                       -606.0
7445             Oct-65            2065-10-01                       -574.0
7481             Apr-66            2066-04-01                       -580.0
7583             Sep-68            2068-09-01                       -609.0
7667             Mar-68            2068-03-01                       -603.0
7893             Sep-62            2062-09-01                       -537.0
8310             Sep-65            2065-09-01                       -573.0
8484             Apr-67            2067-04-01                       -592.0
8806             Oct-63            2063-10-01                       -550.0
8908             Apr-67            2067-04-01                       -592.0
9164             Oct-63            2063-10-01                       -550.0
10344            Oct-64            2064-10-01                       -562.0
10907            May-63            2063-05-01                       -545.0
11288            Jul-67            2067-07-01                       -595.0
11336            Sep-62            2062-09-01                       -537.0
...                 ...                   ...                          ...
458624           Dec-68            2068-12-01                       -612.0
458830           Jun-67            2067-06-01                       -594.0
459081           Oct-68            2068-10-01                       -610.0
459266           Sep-64            2064-09-01                       -561.0
459302           Sep-66            2066-09-01                       -585.0
459736           Sep-66            2066-09-01                       -585.0
460084           Jun-68            2068-06-01                       -606.0
460092           May-68            2068-05-01                       -605.0
460157           May-65            2065-05-01                       -569.0
460243           Jul-68            2068-07-01                       -607.0
460324           Nov-63            2063-11-01                       -551.0
460360           Sep-64            2064-09-01                       -561.0
460365           Jun-65            2065-06-01                       -570.0
460654           Apr-67            2067-04-01                       -592.0
460673           Dec-67            2067-12-01                       -600.0
460762           Mar-67            2067-03-01                       -591.0
461510           Jan-62            2062-01-01                       -529.0
461605           Jun-65            2065-06-01                       -570.0
462539           Jul-65            2065-07-01                       -571.0
463177           Jul-67            2067-07-01                       -595.0
463266           Jan-66            2066-01-01                       -577.0
463371           Mar-63            2063-03-01                       -543.0
463508           Apr-68            2068-04-01                       -604.0
463849           Jun-60            2060-06-01                       -510.0
463887           May-64            2064-05-01                       -557.0
464003           Jan-68            2068-01-01                       -601.0
464260           Jul-66            2066-07-01                       -583.0
465100           Oct-67            2067-10-01                       -598.0
465500           Sep-67            2067-09-01                       -597.0
465655           Jan-56            2056-01-01                       -457.0

[1169 rows x 3 columns]

In [43]:
loan_data['mths_since_earliest_cr_line'][loan_data['mths_since_earliest_cr_line'] < 0] = loan_data['mths_since_earliest_cr_line'].max()

C:\Users\marke\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [44]:
min(loan_data['mths_since_earliest_cr_line'])

73.0

In [45]:
loan_data['mths_since_earliest_cr_line']

0         395.0
1         224.0
2         193.0
3         262.0
4         263.0
5         157.0
6         149.0
7         131.0
8         164.0
9         159.0
10        239.0
11        338.0
12        164.0
13        173.0
14        319.0
15        123.0
16        230.0
17        292.0
18        170.0
19        203.0
20        241.0
21        418.0
22        389.0
23        176.0
24        198.0
25        190.0
26        170.0
27        170.0
28        400.0
29        133.0
          ...
466255    207.0
466256    200.0
466257    389.0
466258    294.0
466259    392.0
466260    243.0
466261    244.0
466262    298.0
466263    233.0
466264    172.0
466265    293.0
466266    285.0
466267    182.0
466268    192.0
466269    212.0
466270    374.0
466271    288.0
466272    198.0
466273    331.0
466274    412.0
466275    289.0
466276    277.0
466277    233.0
466278    186.0
466279    220.0
466280    176.0
466281    246.0
466282    192.0
466283    178.0
466284    214.0
Name: mths_since_earliest_cr_line, Length: 466285, dtype: float64

In [46]:
loan_data['mnts_since_issue_date'] = pd.to_datetime(loan_data['issue_d'], format = '%b-%y')

In [47]:
type(loan_data['mnts_since_issue_date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [48]:
loan_data['mths_since_issue_date'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - loan_data['mnts_since_issue_date']) / np.timedelta64(1, 'M')))

In [49]:
loan_data['mths_since_issue_date'].describe()

count    466285.000000
mean         51.255187
std          14.340154
min          36.000000
25%          41.000000
50%          47.000000
75%          57.000000
max         126.000000
Name: mths_since_issue_date, dtype: float64

# Preprocessing few discrete variables

In [50]:
pd.get_dummies(loan_data['grade'])

        A  B  C  D  E  F  G
0       0  1  0  0  0  0  0
1       0  0  1  0  0  0  0
2       0  0  1  0  0  0  0
3       0  0  1  0  0  0  0
4       0  1  0  0  0  0  0
5       1  0  0  0  0  0  0
6       0  0  1  0  0  0  0
7       0  0  0  0  1  0  0
8       0  0  0  0  0  1  0
9       0  1  0  0  0  0  0
10      0  0  1  0  0  0  0
11      0  1  0  0  0  0  0
12      0  0  1  0  0  0  0
13      0  1  0  0  0  0  0
14      0  1  0  0  0  0  0
15      0  0  0  1  0  0  0
16      0  0  1  0  0  0  0
17      1  0  0  0  0  0  0
18      0  1  0  0  0  0  0
19      1  0  0  0  0  0  0
20      0  0  1  0  0  0  0
21      0  1  0  0  0  0  0
22      0  1  0  0  0  0  0
23      0  1  0  0  0  0  0
24      0  1  0  0  0  0  0
25      0  1  0  0  0  0  0
26      0  0  1  0  0  0  0
27      0  0  0  1  0  0  0
28      0  1  0  0  0  0  0
29      0  1  0  0  0  0  0
...    .. .. .. .. .. .. ..
466255  0  0  0  1  0  0  0
466256  0  0  0  1  0  0  0
466257  0  1  0  0  0  0  0
466258  0  1  0  0  0  0  0
466259  0  0  1  0  0  0  0
466260  0  0  0  0  1  0  0
466261  0  1  0  0  0  0  0
466262  0  0  1  0  0  0  0
466263  0  0  0  1  0  0  0
466264  0  0  1  0  0  0  0
466265  1  0  0  0  0  0  0
466266  1  0  0  0  0  0  0
466267  0  1  0  0  0  0  0
466268  0  0  0  0  1  0  0
466269  0  0  0  0  1  0  0
466270  1  0  0  0  0  0  0
466271  0  0  1  0  0  0  0
466272  0  0  0  0  1  0  0
466273  0  1  0  0  0  0  0
466274  0  1  0  0  0  0  0
466275  0  0  1  0  0  0  0
466276  0  0  0  1  0  0  0
466277  1  0  0  0  0  0  0
466278  0  0  0  1  0  0  0
466279  0  1  0  0  0  0  0
466280  0  0  1  0  0  0  0
466281  0  0  0  1  0  0  0
466282  0  0  0  1  0  0  0
466283  1  0  0  0  0  0  0
466284  0  0  0  1  0  0  0

[466285 rows x 7 columns]

In [51]:
loan_data_dummies = [pd.get_dummies(loan_data['grade'], prefix ='grade', prefix_sep = ':'), 
                     pd.get_dummies(loan_data['sub_grade'], prefix ='sub_grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['home_ownership'], prefix ='home_ownership', prefix_sep = ':'),
                     pd.get_dummies(loan_data['verification_status'], prefix ='verification_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['loan_status'], prefix ='loan_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['purpose'], prefix ='purpose', prefix_sep = ':'),
                     pd.get_dummies(loan_data['addr_state'], prefix ='addr_state', prefix_sep = ':'),
                     pd.get_dummies(loan_data['initial_list_status'], prefix = 'initial_list_status', prefix_sep = ':' )]

In [52]:
loan_data_dummies = pd.concat(loan_data_dummies, axis = 1)

In [53]:
loan_data = pd.concat([loan_data, loan_data_dummies], axis = 1)

In [54]:
loan_data.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 208 columns):
Unnamed: 0                                                         int64
id                                                                 int64
member_id                                                          int64
loan_amnt                                                          int64
funded_amnt                                                        int64
funded_amnt_inv                                                    float64
term                                                               object
int_rate                                                           float64
installment                                                        float64
grade                                                              object
sub_grade                                                          object
emp_title                                                          object
emp_length                                                         object
home_ownership                                                     object
annual_inc                                                         float64
verification_status                                                object
issue_d                                                            object
loan_status                                                        object
pymnt_plan                                                         object
url                                                                object
desc                                                               object
purpose                                                            object
title                                                              object
zip_code                                                           object
addr_state                                                         object
dti                                                                float64
delinq_2yrs                                                        float64
earliest_cr_line                                                   object
inq_last_6mths                                                     float64
mths_since_last_delinq                                             float64
mths_since_last_record                                             float64
open_acc                                                           float64
pub_rec                                                            float64
revol_bal                                                          int64
revol_util                                                         float64
total_acc                                                          float64
initial_list_status                                                object
out_prncp                                                          float64
out_prncp_inv                                                      float64
total_pymnt                                                        float64
total_pymnt_inv                                                    float64
total_rec_prncp                                                    float64
total_rec_int                                                      float64
total_rec_late_fee                                                 float64
recoveries                                                         float64
collection_recovery_fee                                            float64
last_pymnt_d                                                       object
last_pymnt_amnt                                                    float64
next_pymnt_d                                                       object
last_credit_pull_d                                                 object
collections_12_mths_ex_med                                         float64
mths_since_last_major_derog                                        float64
policy_code                                                        int64
application_type                                                   object
annual_inc_joint                                                   float64
dti_joint                                                          float64
verification_status_joint                                          float64
acc_now_delinq                                                     float64
tot_coll_amt                                                       float64
tot_cur_bal                                                        float64
open_acc_6m                                                        float64
open_il_6m                                                         float64
open_il_12m                                                        float64
open_il_24m                                                        float64
mths_since_rcnt_il                                                 float64
total_bal_il                                                       float64
il_util                                                            float64
open_rv_12m                                                        float64
open_rv_24m                                                        float64
max_bal_bc                                                         float64
all_util                                                           float64
total_rev_hi_lim                                                   float64
inq_fi                                                             float64
total_cu_tl                                                        float64
inq_last_12m                                                       float64
emp_length_int                                                     float64
emp_length-int                                                     float64
term_int                                                           int64
earliest_cr_line_date                                              datetime64[ns]
mths_since_earliest_cr_line                                        float64
mnts_since_issue_date                                              datetime64[ns]
mths_since_issue_date                                              float64
grade:A                                                            uint8
grade:B                                                            uint8
grade:C                                                            uint8
grade:D                                                            uint8
grade:E                                                            uint8
grade:F                                                            uint8
grade:G                                                            uint8
sub_grade:A1                                                       uint8
sub_grade:A2                                                       uint8
sub_grade:A3                                                       uint8
sub_grade:A4                                                       uint8
sub_grade:A5                                                       uint8
sub_grade:B1                                                       uint8
sub_grade:B2                                                       uint8
sub_grade:B3                                                       uint8
sub_grade:B4                                                       uint8
sub_grade:B5                                                       uint8
sub_grade:C1                                                       uint8
sub_grade:C2                                                       uint8
sub_grade:C3                                                       uint8
sub_grade:C4                                                       uint8
sub_grade:C5                                                       uint8
sub_grade:D1                                                       uint8
sub_grade:D2                                                       uint8
sub_grade:D3                                                       uint8
sub_grade:D4                                                       uint8
sub_grade:D5                                                       uint8
sub_grade:E1                                                       uint8
sub_grade:E2                                                       uint8
sub_grade:E3                                                       uint8
sub_grade:E4                                                       uint8
sub_grade:E5                                                       uint8
sub_grade:F1                                                       uint8
sub_grade:F2                                                       uint8
sub_grade:F3                                                       uint8
sub_grade:F4                                                       uint8
sub_grade:F5                                                       uint8
sub_grade:G1                                                       uint8
sub_grade:G2                                                       uint8
sub_grade:G3                                                       uint8
sub_grade:G4                                                       uint8
sub_grade:G5                                                       uint8
home_ownership:ANY                                                 uint8
home_ownership:MORTGAGE                                            uint8
home_ownership:NONE                                                uint8
home_ownership:OTHER                                               uint8
home_ownership:OWN                                                 uint8
home_ownership:RENT                                                uint8
verification_status:Not Verified                                   uint8
verification_status:Source Verified                                uint8
verification_status:Verified                                       uint8
loan_status:Charged Off                                            uint8
loan_status:Current                                                uint8
loan_status:Default                                                uint8
loan_status:Does not meet the credit policy. Status:Charged Off    uint8
loan_status:Does not meet the credit policy. Status:Fully Paid     uint8
loan_status:Fully Paid                                             uint8
loan_status:In Grace Period                                        uint8
loan_status:Late (16-30 days)                                      uint8
loan_status:Late (31-120 days)                                     uint8
purpose:car                                                        uint8
purpose:credit_card                                                uint8
purpose:debt_consolidation                                         uint8
purpose:educational                                                uint8
purpose:home_improvement                                           uint8
purpose:house                                                      uint8
purpose:major_purchase                                             uint8
purpose:medical                                                    uint8
purpose:moving                                                     uint8
purpose:other                                                      uint8
purpose:renewable_energy                                           uint8
purpose:small_business                                             uint8
purpose:vacation                                                   uint8
purpose:wedding                                                    uint8
addr_state:AK                                                      uint8
addr_state:AL                                                      uint8
addr_state:AR                                                      uint8
addr_state:AZ                                                      uint8
addr_state:CA                                                      uint8
addr_state:CO                                                      uint8
addr_state:CT                                                      uint8
addr_state:DC                                                      uint8
addr_state:DE                                                      uint8
addr_state:FL                                                      uint8
addr_state:GA                                                      uint8
addr_state:HI                                                      uint8
addr_state:IA                                                      uint8
addr_state:ID                                                      uint8
addr_state:IL                                                      uint8
addr_state:IN                                                      uint8
addr_state:KS                                                      uint8
addr_state:KY                                                      uint8
addr_state:LA                                                      uint8
addr_state:MA                                                      uint8
addr_state:MD                                                      uint8
addr_state:ME                                                      uint8
addr_state:MI                                                      uint8
addr_state:MN                                                      uint8
addr_state:MO                                                      uint8
addr_state:MS                                                      uint8
addr_state:MT                                                      uint8
addr_state:NC                                                      uint8
addr_state:NE                                                      uint8
addr_state:NH                                                      uint8
addr_state:NJ                                                      uint8
addr_state:NM                                                      uint8
addr_state:NV                                                      uint8
addr_state:NY                                                      uint8
addr_state:OH                                                      uint8
addr_state:OK                                                      uint8
addr_state:OR                                                      uint8
addr_state:PA                                                      uint8
addr_state:RI                                                      uint8
addr_state:SC                                                      uint8
addr_state:SD                                                      uint8
addr_state:TN                                                      uint8
addr_state:TX                                                      uint8
addr_state:UT                                                      uint8
addr_state:VA                                                      uint8
addr_state:VT                                                      uint8
addr_state:WA                                                      uint8
addr_state:WI                                                      uint8
addr_state:WV                                                      uint8
addr_state:WY                                                      uint8
initial_list_status:f                                              uint8
initial_list_status:w                                              uint8
dtypes: datetime64[ns](2), float64(50), int64(8), object(22), uint8(126)
memory usage: 347.7+ MB

# Checking for missing value and clean

In [55]:
pd.options.display.max_rows = None
loan_data.isnull().sum()

Unnamed: 0                                                              0
id                                                                      0
member_id                                                               0
loan_amnt                                                               0
funded_amnt                                                             0
funded_amnt_inv                                                         0
term                                                                    0
int_rate                                                                0
installment                                                             0
grade                                                                   0
sub_grade                                                               0
emp_title                                                           27588
emp_length                                                          21008
home_ownership                                                          0
annual_inc                                                              4
verification_status                                                     0
issue_d                                                                 0
loan_status                                                             0
pymnt_plan                                                              0
url                                                                     0
desc                                                               340302
purpose                                                                 0
title                                                                  20
zip_code                                                                0
addr_state                                                              0
dti                                                                     0
delinq_2yrs                                                            29
earliest_cr_line                                                       29
inq_last_6mths                                                         29
mths_since_last_delinq                                             250351
mths_since_last_record                                             403647
open_acc                                                               29
pub_rec                                                                29
revol_bal                                                               0
revol_util                                                            340
total_acc                                                              29
initial_list_status                                                     0
out_prncp                                                               0
out_prncp_inv                                                           0
total_pymnt                                                             0
total_pymnt_inv                                                         0
total_rec_prncp                                                         0
total_rec_int                                                           0
total_rec_late_fee                                                      0
recoveries                                                              0
collection_recovery_fee                                                 0
last_pymnt_d                                                          376
last_pymnt_amnt                                                         0
next_pymnt_d                                                       227214
last_credit_pull_d                                                     42
collections_12_mths_ex_med                                            145
mths_since_last_major_derog                                        367311
policy_code                                                             0
application_type                                                        0
annual_inc_joint                                                   466285
dti_joint                                                          466285
verification_status_joint                                          466285
acc_now_delinq                                                         29
tot_coll_amt                                                        70276
tot_cur_bal                                                         70276
open_acc_6m                                                        466285
open_il_6m                                                         466285
open_il_12m                                                        466285
open_il_24m                                                        466285
mths_since_rcnt_il                                                 466285
total_bal_il                                                       466285
il_util                                                            466285
open_rv_12m                                                        466285
open_rv_24m                                                        466285
max_bal_bc                                                         466285
all_util                                                           466285
total_rev_hi_lim                                                    70276
inq_fi                                                             466285
total_cu_tl                                                        466285
inq_last_12m                                                       466285
emp_length_int                                                          0
emp_length-int                                                          0
term_int                                                                0
earliest_cr_line_date                                                  29
mths_since_earliest_cr_line                                            29
mnts_since_issue_date                                                   0
mths_since_issue_date                                                   0
grade:A                                                                 0
grade:B                                                                 0
grade:C                                                                 0
grade:D                                                                 0
grade:E                                                                 0
grade:F                                                                 0
grade:G                                                                 0
sub_grade:A1                                                            0
sub_grade:A2                                                            0
sub_grade:A3                                                            0
sub_grade:A4                                                            0
sub_grade:A5                                                            0
sub_grade:B1                                                            0
sub_grade:B2                                                            0
sub_grade:B3                                                            0
sub_grade:B4                                                            0
sub_grade:B5                                                            0
sub_grade:C1                                                            0
sub_grade:C2                                                            0
sub_grade:C3                                                            0
sub_grade:C4                                                            0
sub_grade:C5                                                            0
sub_grade:D1                                                            0
sub_grade:D2                                                            0
sub_grade:D3                                                            0
sub_grade:D4                                                            0
sub_grade:D5                                                            0
sub_grade:E1                                                            0
sub_grade:E2                                                            0
sub_grade:E3                                                            0
sub_grade:E4                                                            0
sub_grade:E5                                                            0
sub_grade:F1                                                            0
sub_grade:F2                                                            0
sub_grade:F3                                                            0
sub_grade:F4                                                            0
sub_grade:F5                                                            0
sub_grade:G1                                                            0
sub_grade:G2                                                            0
sub_grade:G3                                                            0
sub_grade:G4                                                            0
sub_grade:G5                                                            0
home_ownership:ANY                                                      0
home_ownership:MORTGAGE                                                 0
home_ownership:NONE                                                     0
home_ownership:OTHER                                                    0
home_ownership:OWN                                                      0
home_ownership:RENT                                                     0
verification_status:Not Verified                                        0
verification_status:Source Verified                                     0
verification_status:Verified                                            0
loan_status:Charged Off                                                 0
loan_status:Current                                                     0
loan_status:Default                                                     0
loan_status:Does not meet the credit policy. Status:Charged Off         0
loan_status:Does not meet the credit policy. Status:Fully Paid          0
loan_status:Fully Paid                                                  0
loan_status:In Grace Period                                             0
loan_status:Late (16-30 days)                                           0
loan_status:Late (31-120 days)                                          0
purpose:car                                                             0
purpose:credit_card                                                     0
purpose:debt_consolidation                                              0
purpose:educational                                                     0
purpose:home_improvement                                                0
purpose:house                                                           0
purpose:major_purchase                                                  0
purpose:medical                                                         0
purpose:moving                                                          0
purpose:other                                                           0
purpose:renewable_energy                                                0
purpose:small_business                                                  0
purpose:vacation                                                        0
purpose:wedding                                                         0
addr_state:AK                                                           0
addr_state:AL                                                           0
addr_state:AR                                                           0
addr_state:AZ                                                           0
addr_state:CA                                                           0
addr_state:CO                                                           0
addr_state:CT                                                           0
addr_state:DC                                                           0
addr_state:DE                                                           0
addr_state:FL                                                           0
addr_state:GA                                                           0
addr_state:HI                                                           0
addr_state:IA                                                           0
addr_state:ID                                                           0
addr_state:IL                                                           0
addr_state:IN                                                           0
addr_state:KS                                                           0
addr_state:KY                                                           0
addr_state:LA                                                           0
addr_state:MA                                                           0
addr_state:MD                                                           0
addr_state:ME                                                           0
addr_state:MI                                                           0
addr_state:MN                                                           0
addr_state:MO                                                           0
addr_state:MS                                                           0
addr_state:MT                                                           0
addr_state:NC                                                           0
addr_state:NE                                                           0
addr_state:NH                                                           0
addr_state:NJ                                                           0
addr_state:NM                                                           0
addr_state:NV                                                           0
addr_state:NY                                                           0
addr_state:OH                                                           0
addr_state:OK                                                           0
addr_state:OR                                                           0
addr_state:PA                                                           0
addr_state:RI                                                           0
addr_state:SC                                                           0
addr_state:SD                                                           0
addr_state:TN                                                           0
addr_state:TX                                                           0
addr_state:UT                                                           0
addr_state:VA                                                           0
addr_state:VT                                                           0
addr_state:WA                                                           0
addr_state:WI                                                           0
addr_state:WV                                                           0
addr_state:WY                                                           0
initial_list_status:f                                                   0
initial_list_status:w                                                   0
dtype: int64

In [56]:
pd.options.display.max_rows = 100

In [57]:
loan_data['total_rev_hi_lim'].fillna(loan_data['funded_amnt'], inplace = True)

In [58]:
loan_data['total_rev_hi_lim'].isnull().sum()

0

In [65]:
loan_data['annual_inc'].mean()

73277.38147046504

In [66]:
loan_data['annual_inc'] = loan_data['annual_inc'].fillna(value=loan_data['annual_inc'].mean())

In [67]:
loan_data['annual_inc'].isnull().sum()

0

In [70]:
loan_data['mths_since_earliest_cr_line'].fillna(value=0, inplace=True)
loan_data['acc_now_delinq'].fillna(value=0, inplace=True)
loan_data['total_acc'].fillna(value=0, inplace=True)
loan_data['pub_rec'].fillna(value=0, inplace=True)
loan_data['open_acc'].fillna(value=0, inplace=True)
loan_data['inq_last_6mths'].fillna(value=0, inplace=True)
loan_data['delinq_2yrs'].fillna(value=0, inplace=True)
loan_data['emp_length_int'].fillna(value=0, inplace=True)

In [72]:
loan_data['total_acc'].isnull().sum()

0

# PD Model

## Data Preparation

### Dependent Variable. Good/Bad (Default) Definition. Default and Non-default Accounts.

In [73]:
loan_data['loan_status'].unique()

array(['Fully Paid', 'Charged Off', 'Current', 'Default',
       'Late (31-120 days)', 'In Grace Period', 'Late (16-30 days)',
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off'],
      dtype=object)

In [75]:
loan_data['loan_status'].value_counts()

Current                                                224226
Fully Paid                                             184739
Charged Off                                             42475
Late (31-120 days)                                       6900
In Grace Period                                          3146
Does not meet the credit policy. Status:Fully Paid       1988
Late (16-30 days)                                        1218
Default                                                   832
Does not meet the credit policy. Status:Charged Off       761
Name: loan_status, dtype: int64

In [76]:
loan_data['loan_status'].value_counts() / loan_data['loan_status'].count()

Current                                                0.480878
Fully Paid                                             0.396193
Charged Off                                            0.091092
Late (31-120 days)                                     0.014798
In Grace Period                                        0.006747
Does not meet the credit policy. Status:Fully Paid     0.004263
Late (16-30 days)                                      0.002612
Default                                                0.001784
Does not meet the credit policy. Status:Charged Off    0.001632
Name: loan_status, dtype: float64

In [81]:
import numpy as np
loan_data['good_bad'] = np.where(loan_data['loan_status'].isin(['Charged Off', 'Default',
                                                                'Does not meet the credit policy. Status:Charged Off',
                                                                'Late (31-120 days)']), 0, 1)

In [82]:
loan_data['good_bad']

0         1
1         0
2         1
3         1
4         1
5         1
6         1
7         1
8         0
9         0
10        1
11        1
12        0
13        1
14        0
15        1
16        1
17        1
18        1
19        1
20        1
21        0
22        1
23        1
24        0
25        1
26        0
27        0
28        1
29        1
30        1
31        1
32        1
33        1
34        1
35        1
36        1
37        1
38        1
39        1
40        1
41        1
42        1
43        1
44        1
45        1
46        0
47        1
48        1
49        1
         ..
466235    1
466236    1
466237    1
466238    1
466239    1
466240    1
466241    1
466242    1
466243    1
466244    1
466245    1
466246    1
466247    1
466248    1
466249    1
466250    1
466251    0
466252    0
466253    1
466254    0
466255    1
466256    0
466257    1
466258    1
466259    1
466260    1
466261    1
466262    1
466263    1
466264    1
466265    1
466266    1
466267    1
466268    1
466269    1
466270    1
466271    1
466272    1
466273    1
466274    1
466275    1
466276    0
466277    0
466278    1
466279    1
466280    1
466281    0
466282    1
466283    1
466284    1
Name: good_bad, Length: 466285, dtype: int32

# Splitting Data

In [83]:
from sklearn.model_selection import train_test_split

In [85]:
train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'])

[        Unnamed: 0        id  member_id  loan_amnt  funded_amnt  \
 179839      179839   2378131    2840532      19000        19000
 342393      342393  21461297   23784148      15000        15000
 294809      294809  29213556   31746719      23000        23000
 328862      328862  23914559   26287359       7600         7600
 302337      302337  28052722   30565875      28000        28000
 191558      191558   1608803    1880577       7200         7200
 20910        20910    651012     832785       6000         6000
 383508      383508  17282664   19415211       5200         5200
 105656      105656   6523960    8075891       5500         5500
 439410      439410  11698514   13670682      17000        17000
 264987      264987  33300818   35944089       5000         5000
 277822      277822  31157458   33730709       1800         1800
 301036      301036  28522709   31045842       9000         9000
 268988      268988  31237384   33810619      20950        20950
 410858      410858  13607541    8122347      15000        15000
 415680      415680  13427493   15479784      10000        10000
 330254      330254  23843782   26216669      10000        10000
 301264      301264  28602586   31125698       8000         8000
 56348        56348   9144616   10976761      10000        10000
 146749      146749   4295012    5467202      21200        21200
 143759      143759   4568257    5820589      31300        31300
 139119      139119   5040861    6343334       7775         7775
 342689      342689  19116703   21319406      16000        16000
 424234      424234  12917199   14949390      18000        18000
 442234      442234  11935199   13927355      35000        35000
 246150      246150  32939926   35583158      20000        20000
 169467      169467   3159943    3872460       9000         9000
 420342      420342  13176424   15208621       3000         3000
 139458      139458   5039585    6341980      10000        10000
 385878      385878  16413146   18495542      18000        18000
 45522        45522  10065564   11917670      34475        34475
 159025      159025   3639259    4591753       4000         4000
 226298      226298   1140871    1381537      10400        10400
 197587      197587   1531143    1795275      10000        10000
 381742      381742  17532872   19655422      12500        12500
 204423      204423   1456157    1710606      21000        21000
 382522      382522  17103170   19225706       8000         8000
 228769      228769   1104473    1340827      18400        18400
 190584      190584   1622809    1894828      18000        18000
 338842      338842  21129516   23412365      13150        13150
 125731      125731   5760021    7192078      24500        24500
 39387        39387    231321     214993      10000        10000
 299271      299271  28593312   31116471      12000        12000
 170541      170541   3195625    3928401      26000        26000
 24304        24304    602729     773345      25000        25000
 243170      243170  35054029   37737330      20000        20000
 264979      264979  33160705   35803968      12000        12000
 185819      185819   2004923    2347098      35000        35000
 154353      154353   3676542    4639776      15000        15000
 208217      208217   1415806    1665770      16000        16000
 ...            ...       ...        ...        ...          ...
 127274      127274   5776729    7208898      14550        14550
 374847      374847  18274384   20417086      11975        11975
 241984      241984  35369461   38057974       9600         9600
 394782      394782  13398617   15450909      25000        25000
 125196      125196   5781601    7213459      26000        26000
 16596        16596    730728     926719      20000        20000
 254742      254742  34473520   37136865      15800        15800
 157901      157901   3195050    3927797      17000        17000
 208437      208437   1412845    1662766      17450        17450
 174501      174501   3006629    3638992       6300         6300
 245648      245648  35441152   38138366      12500        12500
 211212      211212   1377060    1621236      35000        35000
 69437        69437   8608049   10360010      15000        15000
 366777      366777  19106987   14608924       6000         6000
 30038        30038    515743     666641      12000        12000
 438971      438971  12265573   14257733       8000         8000
 185655      185655   1945665    2277872       4400         4400
 59689        59689   9009299   10801201      25000        25000
 138546      138546   5094695    6416872      20000        20000
 52541        52541   9474966   11307090      27000        27000
 308923      308923  26889992   29372979      12000        12000
 113812      113812   6326848    3476898      11000        11000
 155343      155343   3704151    4847625      12375        12375
 285919      285919  30225487   32768690      14400        14400
 303293      303293  28252282   30765415       5000         5000
 434113      434113  12397575   14409695       7000         7000
 57315        57315   9056800   10116823      20000        20000
 464155      464155  10070584   11922117       7125         7125
 405267      405267  14479826   16542118      30000        30000
 55673        55673   8598365   10350224       6000         6000
 289652      289652  29774955   32328163      13000        13000
 185245      185245   2086465    2418753      22500        22500
 68034        68034   8624691   10396829      11600        11600
 276996      276996  31667224   34260392      11000        11000
 95096        95096   7045675    8707800      25000        25000
 91072        91072   7094158    8755633       6375         6375
 135701      135701   5354697    6706852       4000         4000
 455257      455257  10133036   11984282      18000        18000
 114206      114206   6295786    7827778      18000        18000
 39189        39189    265904     264483      16000        16000
 97203        97203   6819550    8441176      22750        22750
 341193      341193  21670904   23993852       5000         5000
 459079      459079  10576054   12458110      15000        15000
 80669        80669   7695937    9398064      24000        24000
 153611      153611   3925710    5017974      24000        24000
 445562      445562  11716210   13688377       6400         6400
 333308      333308  23183231   25536094      15500        15500
 408513      408513  14458219   16520579      13000        13000
 283632      283632  30345699   32888892      12000        12000
 448060      448060  11405998   13338183      35000        35000

         funded_amnt_inv        term  int_rate  installment grade sub_grade  \
 179839     19000.000000   36 months     11.14       623.30     B        B2
 342393     15000.000000   36 months     14.49       516.25     C        C4
 294809     23000.000000   60 months     18.99       596.51     E        E1
 328862      7600.000000   36 months     10.15       245.77     B        B2
 302337     28000.000000   60 months     10.99       608.65     B        B3
 191558      7200.000000   36 months     17.77       259.47     D        D1
 20910       5983.873723   36 months      5.42       180.96     A        A1
 383508      5200.000000   36 months      8.39       163.89     A        A5
 105656      5500.000000   36 months     11.55       181.50     B        B3
 439410     17000.000000   60 months     14.16       396.98     C        C2
 264987      5000.000000   36 months     11.67       165.29     B        B4
 277822      1800.000000   36 months     10.99        58.93     B        B3
 301036      9000.000000   36 months      7.69       280.75     A        A4
 268988     20950.000000   60 months     16.29       512.70     D        D2
 410858     15000.000000   36 months     19.99       557.38     E        E1
 415680     10000.000000   36 months      8.90       317.54     A        A5
 330254     10000.000000   36 months      9.17       318.79     B        B1
 301264      8000.000000   36 months      8.39       252.14     A        A5
 56348      10000.000000   36 months      7.90       312.91     A        A4
 146749     21200.000000   60 months     17.27       529.96     C        C5
 143759     31300.000000   60 months     17.77       790.91     D        D1
 139119      7775.000000   36 months      8.90       246.89     A        A5
 342689     16000.000000   36 months     10.15       517.41     B        B2
 424234     18000.000000   36 months      9.67       578.03     B        B1
 442234     35000.000000   36 months     15.61      1223.77     C        C5
 246150     20000.000000   60 months     12.99       454.96     C        C2
 169467      9000.000000   36 months     14.33       309.05     C        C1
 420342      3000.000000   36 months     12.49       100.35     B        B4
 139458     10000.000000   36 months     12.12       332.72     B        B3
 385878     17950.000000   60 months     16.99       447.25     D        D3
 45522      34475.000000   60 months     21.48       942.00     E        E2
 159025      4000.000000   36 months     13.11       134.99     B        B4
 226298     10400.000000   36 months     12.12       346.03     B        B3
 197587     10000.000000   36 months     10.16       323.43     B        B1
 381742     12500.000000   36 months      9.17       398.49     B        B1
 204423     21000.000000   60 months     11.14       458.06     B        B2
 382522      8000.000000   36 months     13.35       270.91     C        C2
 228769     18400.000000   36 months     12.42       614.85     B        B4
 190584     17925.000000   36 months     14.09       615.99     B        B5
 338842     13150.000000   60 months     18.99       341.05     E        E1
 125731     24500.000000   60 months     16.29       599.58     C        C4
 39387       1228.060000   36 months      7.75       312.22     A        A3
 299271     12000.000000   60 months     18.99       311.23     E        E1
 170541     26000.000000   36 months     15.31       905.26     C        C2
 24304      23578.682770   36 months     14.83       864.56     D        D3
 243170     20000.000000   36 months      7.49       622.04     A        A4
 264979     12000.000000   60 months     13.98       279.10     C        C3
 185819     34750.000000   36 months     15.31      1218.61     C        C2
 154353     14950.000000   60 months     15.31       359.30     C        C2
 208217     15998.909460   36 months     16.29       564.81     C        C4
 ...                 ...         ...       ...          ...   ...       ...
 127274     14450.000000   36 months     10.16       470.59     B        B1
 374847     11975.000000   36 months     12.99       403.43     C        C1
 241984      9600.000000   36 months     12.99       323.42     C        C2
 394782     24875.000000   60 months     21.99       690.34     E        E4
 125196     26000.000000   60 months     13.11       593.05     B        B4
 16596      20000.000000   36 months     10.37       648.83     B        B3
 254742     15800.000000   36 months     11.99       524.72     B        B5
 157901     16975.000000   36 months      7.90       531.94     A        A4
 208437     17450.000000   60 months     21.00       472.09     E        E2
 174501      6275.000000   36 months     15.80       220.87     C        C3
 245648     12500.000000   36 months      7.49       388.78     A        A4
 211212     35000.000000   60 months     21.97       966.07     E        E5
 69437      15000.000000   36 months     13.67       510.27     B        B5
 366777      6000.000000   36 months     14.99       207.97     C        C5
 30038      11894.840000   36 months     11.36       394.92     B        B5
 438971      8000.000000   36 months      9.67       256.90     B        B1
 185655      4400.000000   36 months     15.31       153.20     C        C2
 59689      25000.000000   36 months      9.67       802.82     B        B1
 138546     20000.000000   60 months     21.49       546.60     E        E3
 52541      27000.000000   60 months     14.98       642.05     C        C3
 308923     12000.000000   36 months      6.49       367.74     A        A2
 113812     11000.000000   36 months     21.15       415.28     E        E2
 155343     12375.000000   36 months     11.14       405.97     B        B2
 285919     14400.000000   36 months      6.49       441.29     A        A2
 303293      5000.000000   36 months     16.29       176.51     D        D2
 434113      7000.000000   36 months      6.62       214.93     A        A2
 57315      20000.000000   36 months     17.10       714.06     C        C5
 464155      7125.000000   36 months     22.90       275.44     E        E4
 405267     30000.000000   60 months     21.18       814.65     E        E3
 55673       6000.000000   36 months      6.03       182.62     A        A1
 289652     13000.000000   36 months      7.69       405.52     A        A4
 185245     22500.000000   36 months     20.49       841.81     E        E1
 68034      11600.000000   36 months      6.03       353.06     A        A1
 276996     11000.000000   36 months     11.67       363.63     B        B4
 95096      25000.000000   36 months     12.35       834.55     B        B4
 91072       6375.000000   36 months      9.71       204.84     B        B1
 135701      4000.000000   36 months     19.72       148.09     D        D5
 455257     18000.000000   36 months     14.98       623.80     C        C3
 114206     18000.000000   60 months     14.33       421.92     C        C2
 39189       1800.000000   36 months     14.18       548.25     E        E1
 97203      22750.000000   60 months     20.31       606.67     D        D5
 341193      5000.000000   36 months     13.35       169.32     C        C2
 459079     15000.000000   36 months     16.99       534.72     D        D1
 80669      24000.000000   36 months      8.60       758.74     A        A4
 153611     24000.000000   36 months      7.62       747.88     A        A3
 445562      6400.000000   36 months     14.98       221.80     C        C3
 333308     15500.000000   36 months      6.03       471.76     A        A1
 408513     13000.000000   60 months     15.61       313.45     C        C5
 283632     12000.000000   36 months     12.99       404.27     C        C1
 448060     35000.000000   60 months     18.25       893.54     D        D3

                                   emp_title emp_length home_ownership  \
 179839                          Mozilla Inc   < 1 year           RENT
 342393                      Principal Coach    6 years       MORTGAGE
 294809                      Program Analyst  10+ years       MORTGAGE
 328862                              Bodyman    2 years       MORTGAGE
 302337             Logistics Program Manaer    3 years       MORTGAGE
 191558                        VisionIT - HP     1 year       MORTGAGE
 20910                 Jackson Health System  10+ years       MORTGAGE
 383508                         Receptionist    7 years           RENT
 105656                                 RLSD     1 year           RENT
 439410                     Systems Engineer  10+ years       MORTGAGE
 264987             Food Service Coordinator  10+ years           RENT
 277822                               Hr Dir  10+ years       MORTGAGE
 301036                  Development Manager     1 year       MORTGAGE
 268988                       Vice President  10+ years       MORTGAGE
 410858                     Telecom engineer   < 1 year           RENT
 415680                               driver    8 years           RENT
 330254                           ironworker  10+ years            OWN
 301264                               Driver    6 years       MORTGAGE
 56348                              Screener    6 years       MORTGAGE
 146749                            M-I Swaco    2 years           RENT
 143759  Jemez Mountain Electric Cooperative  10+ years       MORTGAGE
 139119                                  NaN    3 years           RENT
 342689       senior loss control technician    5 years       MORTGAGE
 424234                   Operations Manager    7 years           RENT
 442234            TransportaciÃÂ³n officer    6 years       MORTGAGE
 246150                         Quality tech  10+ years       MORTGAGE
 169467                I 95 TOYOTA AND SCION    9 years       MORTGAGE
 420342                    manager assistant     1 year           RENT
 139458                                  NaN        NaN            OWN
 385878                                  RN    < 1 year       MORTGAGE
 45522                              mechanic    7 years       MORTGAGE
 159025                     Charter One Bank    9 years       MORTGAGE
 226298                        Ernst & Young   < 1 year           RENT
 197587                              Kavlico     1 year           RENT
 381742                       Police officer   < 1 year           RENT
 204423                   Laird Technologies    6 years       MORTGAGE
 382522                     Property Manager    2 years       MORTGAGE
 228769           Texas City Fire Department    3 years           RENT
 190584                                  NaN        NaN            OWN
 338842                      Data Entry lerk    5 years           RENT
 125731                                  FBI    3 years       MORTGAGE
 39387                                   ups    5 years           NONE
 299271                      Remote Services   < 1 year            OWN
 170541                      CALIBER FUNDING   < 1 year           RENT
 24304                    New Logic Research    3 years           RENT
 243170                     Graphics Manager  10+ years       MORTGAGE
 264979                               driver    8 years       MORTGAGE
 185819                                 MWAA  10+ years           RENT
 154353      Federal Bureau of Investigation  10+ years           RENT
 208217                    Kaiser Permanente  10+ years       MORTGAGE
 ...                                     ...        ...            ...
 127274                       JPMorgan Chase    2 years           RENT
 374847                                Clerk  10+ years       MORTGAGE
 241984                 Sr. Review Appraiser  10+ years           RENT
 394782         Supply Management Specialist  10+ years           RENT
 125196              Del tex management corp  10+ years       MORTGAGE
 16596                               US Army  10+ years           RENT
 254742             Auto Damage Appraiser II   < 1 year           RENT
 157901           After Hours Printing, Inc.  10+ years           RENT
 208437               Ken Batchelor Cadillac  10+ years       MORTGAGE
 174501                     General Electric    5 years           RENT
 245648                      Network Analyst  10+ years       MORTGAGE
 211212            Skidmore,Owings & Merrill    2 years           RENT
 69437                    Judicial assistant  10+ years       MORTGAGE
 366777             Poison Control Specialis  10+ years       MORTGAGE
 30038               United Methodist Church    7 years       MORTGAGE
 438971  Therapist/Assistant ACT Team Leader    7 years       MORTGAGE
 185655         Atlantic Plant Services, LLC  10+ years           RENT
 59689                            Controller    6 years       MORTGAGE
 138546              Village of Hanover Park    6 years       MORTGAGE
 52541                   Contracting Officer  10+ years       MORTGAGE
 308923                        Sales Manager   < 1 year           RENT
 113812              fairmount longterm care    5 years           RENT
 155343            caliber collision centers    6 years       MORTGAGE
 285919                            Physician     1 year           RENT
 303293                      PAYROLL MANAGER  10+ years           RENT
 434113                      Project Manager    3 years           RENT

In [86]:
loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'])

In [87]:
loan_data_inputs_train.shape

(349713, 208)

In [88]:
loan_data_inputs_test.shape

(116572, 208)

In [89]:
loan_data_targets_train.shape

(349713,)

In [90]:
loan_data_targets_test.shape

(116572,)

In [ ]:
loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'])

In [94]:

loan_data.info(verbose= True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 209 columns):
Unnamed: 0                                                         int64
id                                                                 int64
member_id                                                          int64
loan_amnt                                                          int64
funded_amnt                                                        int64
funded_amnt_inv                                                    float64
term                                                               object
int_rate                                                           float64
installment                                                        float64
grade                                                              object
sub_grade                                                          object
emp_title                                                          object
emp_length                                                         object
home_ownership                                                     object
annual_inc                                                         float64
verification_status                                                object
issue_d                                                            object
loan_status                                                        object
pymnt_plan                                                         object
url                                                                object
desc                                                               object
purpose                                                            object
title                                                              object
zip_code                                                           object
addr_state                                                         object
dti                                                                float64
delinq_2yrs                                                        float64
earliest_cr_line                                                   object
inq_last_6mths                                                     float64
mths_since_last_delinq                                             float64
mths_since_last_record                                             float64
open_acc                                                           float64
pub_rec                                                            float64
revol_bal                                                          int64
revol_util                                                         float64
total_acc                                                          float64
initial_list_status                                                object
out_prncp                                                          float64
out_prncp_inv                                                      float64
total_pymnt                                                        float64
total_pymnt_inv                                                    float64
total_rec_prncp                                                    float64
total_rec_int                                                      float64
total_rec_late_fee                                                 float64
recoveries                                                         float64
collection_recovery_fee                                            float64
last_pymnt_d                                                       object
last_pymnt_amnt                                                    float64
next_pymnt_d                                                       object
last_credit_pull_d                                                 object
collections_12_mths_ex_med                                         float64
mths_since_last_major_derog                                        float64
policy_code                                                        int64
application_type                                                   object
annual_inc_joint                                                   float64
dti_joint                                                          float64
verification_status_joint                                          float64
acc_now_delinq                                                     float64
tot_coll_amt                                                       float64
tot_cur_bal                                                        float64
open_acc_6m                                                        float64
open_il_6m                                                         float64
open_il_12m                                                        float64
open_il_24m                                                        float64
mths_since_rcnt_il                                                 float64
total_bal_il                                                       float64
il_util                                                            float64
open_rv_12m                                                        float64
open_rv_24m                                                        float64
max_bal_bc                                                         float64
all_util                                                           float64
total_rev_hi_lim                                                   float64
inq_fi                                                             float64
total_cu_tl                                                        float64
inq_last_12m                                                       float64
emp_length_int                                                     float64
emp_length-int                                                     float64
term_int                                                           int64
earliest_cr_line_date                                              datetime64[ns]
mths_since_earliest_cr_line                                        float64
mnts_since_issue_date                                              datetime64[ns]
mths_since_issue_date                                              float64
grade:A                                                            uint8
grade:B                                                            uint8
grade:C                                                            uint8
grade:D                                                            uint8
grade:E                                                            uint8
grade:F                                                            uint8
grade:G                                                            uint8
sub_grade:A1                                                       uint8
sub_grade:A2                                                       uint8
sub_grade:A3                                                       uint8
sub_grade:A4                                                       uint8
sub_grade:A5                                                       uint8
sub_grade:B1                                                       uint8
sub_grade:B2                                                       uint8
sub_grade:B3                                                       uint8
sub_grade:B4                                                       uint8
sub_grade:B5                                                       uint8
sub_grade:C1                                                       uint8
sub_grade:C2                                                       uint8
sub_grade:C3                                                       uint8
sub_grade:C4                                                       uint8
sub_grade:C5                                                       uint8
sub_grade:D1                                                       uint8
sub_grade:D2                                                       uint8
sub_grade:D3                                                       uint8
sub_grade:D4                                                       uint8
sub_grade:D5                                                       uint8
sub_grade:E1                                                       uint8
sub_grade:E2                                                       uint8
sub_grade:E3                                                       uint8
sub_grade:E4                                                       uint8
sub_grade:E5                                                       uint8
sub_grade:F1                                                       uint8
sub_grade:F2                                                       uint8
sub_grade:F3                                                       uint8
sub_grade:F4                                                       uint8
sub_grade:F5                                                       uint8
sub_grade:G1                                                       uint8
sub_grade:G2                                                       uint8
sub_grade:G3                                                       uint8
sub_grade:G4                                                       uint8
sub_grade:G5                                                       uint8
home_ownership:ANY                                                 uint8
home_ownership:MORTGAGE                                            uint8
home_ownership:NONE                                                uint8
home_ownership:OTHER                                               uint8
home_ownership:OWN                                                 uint8
home_ownership:RENT                                                uint8
verification_status:Not Verified                                   uint8
verification_status:Source Verified                                uint8
verification_status:Verified                                       uint8
loan_status:Charged Off                                            uint8
loan_status:Current                                                uint8
loan_status:Default                                                uint8
loan_status:Does not meet the credit policy. Status:Charged Off    uint8
loan_status:Does not meet the credit policy. Status:Fully Paid     uint8
loan_status:Fully Paid                                             uint8
loan_status:In Grace Period                                        uint8
loan_status:Late (16-30 days)                                      uint8
loan_status:Late (31-120 days)                                     uint8
purpose:car                                                        uint8
purpose:credit_card                                                uint8
purpose:debt_consolidation                                         uint8
purpose:educational                                                uint8
purpose:home_improvement                                           uint8
purpose:house                                                      uint8
purpose:major_purchase                                             uint8
purpose:medical                                                    uint8
purpose:moving                                                     uint8
purpose:other                                                      uint8
purpose:renewable_energy                                           uint8
purpose:small_business                                             uint8
purpose:vacation                                                   uint8
purpose:wedding                                                    uint8
addr_state:AK                                                      uint8
addr_state:AL                                                      uint8
addr_state:AR                                                      uint8
addr_state:AZ                                                      uint8
addr_state:CA                                                      uint8
addr_state:CO                                                      uint8
addr_state:CT                                                      uint8
addr_state:DC                                                      uint8
addr_state:DE                                                      uint8
addr_state:FL                                                      uint8
addr_state:GA                                                      uint8
addr_state:HI                                                      uint8
addr_state:IA                                                      uint8
addr_state:ID                                                      uint8
addr_state:IL                                                      uint8
addr_state:IN                                                      uint8
addr_state:KS                                                      uint8
addr_state:KY                                                      uint8
addr_state:LA                                                      uint8
addr_state:MA                                                      uint8
addr_state:MD                                                      uint8
addr_state:ME                                                      uint8
addr_state:MI                                                      uint8
addr_state:MN                                                      uint8
addr_state:MO                                                      uint8
addr_state:MS                                                      uint8
addr_state:MT                                                      uint8
addr_state:NC                                                      uint8
addr_state:NE                                                      uint8
addr_state:NH                                                      uint8
addr_state:NJ                                                      uint8
addr_state:NM                                                      uint8
addr_state:NV                                                      uint8
addr_state:NY                                                      uint8
addr_state:OH                                                      uint8
addr_state:OK                                                      uint8
addr_state:OR                                                      uint8
addr_state:PA                                                      uint8
addr_state:RI                                                      uint8
addr_state:SC                                                      uint8
addr_state:SD                                                      uint8
addr_state:TN                                                      uint8
addr_state:TX                                                      uint8
addr_state:UT                                                      uint8
addr_state:VA                                                      uint8
addr_state:VT                                                      uint8
addr_state:WA                                                      uint8
addr_state:WI                                                      uint8
addr_state:WV                                                      uint8
addr_state:WY                                                      uint8
initial_list_status:f                                              uint8
initial_list_status:w                                              uint8
good_bad                                                           int32
dtypes: datetime64[ns](2), float64(50), int32(1), int64(8), object(22), uint8(126)
memory usage: 349.5+ MB

In [95]:
loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'], test_size = 0.2, random_state = 42)

In [96]:
loan_data_inputs_train.shape

(373028, 208)

In [97]:
loan_data_inputs_test.shape

(93257, 208)